!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Max J. Hoffmann.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmcos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist
use kind_values
use base, only: &
    update_accum_rate, &
    update_integ_rate, &
    determine_procsite, &
    update_clocks, &
    avail_sites, &
    null_species, &
    increment_procstat

use lattice, only: &
    ruo2, &
    ruo2_bridge, &
    ruo2_cus, &
    allocate_system, &
    nr2lattice, &
    lattice2nr, &
    add_proc, &
    can_do, &
    set_rate_const, &
    replace_species, &
    del_proc, &
    reset_site, &
    system_size, &
    spuck, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 3
integer(kind=iint), parameter, public :: CO = 0
integer(kind=iint), parameter, public :: O = 1
integer(kind=iint), parameter, public :: empty = 2
integer(kind=iint), public :: default_species = empty


! Process constants

integer(kind=iint), parameter, public :: CO_adsorption_bridge = 1
integer(kind=iint), parameter, public :: CO_adsorption_cus = 2
integer(kind=iint), parameter, public :: CO_desorption_bridge = 3
integer(kind=iint), parameter, public :: CO_desorption_cus = 4
integer(kind=iint), parameter, public :: COdiff_bridge_down = 5
integer(kind=iint), parameter, public :: COdiff_bridge_left = 6
integer(kind=iint), parameter, public :: COdiff_bridge_right = 7
integer(kind=iint), parameter, public :: COdiff_bridge_up = 8
integer(kind=iint), parameter, public :: COdiff_cus_down = 9
integer(kind=iint), parameter, public :: COdiff_cus_left = 10
integer(kind=iint), parameter, public :: COdiff_cus_right = 11
integer(kind=iint), parameter, public :: COdiff_cus_up = 12
integer(kind=iint), parameter, public :: O2_adsorption_bridge_right = 13
integer(kind=iint), parameter, public :: O2_adsorption_bridge_up = 14
integer(kind=iint), parameter, public :: O2_adsorption_cus_right = 15
integer(kind=iint), parameter, public :: O2_adsorption_cus_up = 16
integer(kind=iint), parameter, public :: O2_desorption_bridge_right = 17
integer(kind=iint), parameter, public :: O2_desorption_bridge_up = 18
integer(kind=iint), parameter, public :: O2_desorption_cus_right = 19
integer(kind=iint), parameter, public :: O2_desorption_cus_up = 20
integer(kind=iint), parameter, public :: Odiff_bridge_down = 21
integer(kind=iint), parameter, public :: Odiff_bridge_left = 22
integer(kind=iint), parameter, public :: Odiff_bridge_right = 23
integer(kind=iint), parameter, public :: Odiff_bridge_up = 24
integer(kind=iint), parameter, public :: Odiff_cus_down = 25
integer(kind=iint), parameter, public :: Odiff_cus_left = 26
integer(kind=iint), parameter, public :: Odiff_cus_right = 27
integer(kind=iint), parameter, public :: Odiff_cus_up = 28
integer(kind=iint), parameter, public :: React_bridge_down = 29
integer(kind=iint), parameter, public :: React_bridge_left = 30
integer(kind=iint), parameter, public :: React_bridge_right = 31
integer(kind=iint), parameter, public :: React_bridge_up = 32
integer(kind=iint), parameter, public :: React_cus_down = 33
integer(kind=iint), parameter, public :: React_cus_left = 34
integer(kind=iint), parameter, public :: React_cus_right = 35
integer(kind=iint), parameter, public :: React_cus_up = 36


integer(kind=iint), parameter, public :: representation_length = 31
integer(kind=iint), public :: seed_size = 33
integer(kind=iint), public :: seed ! random seed
integer(kind=iint), public, dimension(:), allocatable :: seed_arr ! random seed


integer(kind=iint), parameter, public :: nr_of_proc = 36


contains

subroutine do_kmc_steps(n)

!****f* proclist/do_kmc_steps
! FUNCTION
!    Performs ``n`` kMC step.
!    If one has to run many steps without evaluation
!    do_kmc_steps might perform a little better.
!    * first update clock
!    * then configuration sampling step
!    * last execute process
!
! ARGUMENTS
!
!    ``n`` : Number of steps to run
!******
    integer(kind=ilong), intent(in) :: n

    integer(kind=ilong) :: i
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    do i = 1, n
    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
    call run_proc_nr(proc_nr, nr_site)
    enddo

end subroutine do_kmc_steps

subroutine do_kmc_steps_time(t, n, num_iter)
!****f* proclist/do_kmc_steps_time
! FUNCTION
!    Performs a variable number of KMC steps to try to match the requested
!    simulation time as closely as possible without going over. This routine
!    always performs at least one KMC step before terminating.
!    * Determine the time step for the next process
!    * If the time limit is not exceeded, update clocks, rates, execute process,
!      etc.; otherwise, abort.
!    Ideally we would use state(seed_size) but that was not working, so hardcoded size.
!
! ARGUMENTS
!
!    ``t`` : Requested simulation time increment (input)
!    ``n`` : Maximum number of steps to run (input)
!    ``num_iter`` : the number of executed iterations (output)
!******
    use base, only: get_accum_rate
    real(kind=rdouble), intent(in) :: t
    integer(kind=ilong), intent(in) :: n
    integer(kind=ilong), intent(out) :: num_iter

    integer(kind=ilong) :: i
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr
    integer(kind=iint) :: state(33)
    real(kind=rdouble) :: time_step, loop_kmc_time, accum_rate

    loop_kmc_time = 0
    num_iter = 0
    do i = 1, n
      call random_seed(get=state)
      call random_number(ran_time)
      call random_number(ran_proc)
      call random_number(ran_site)
      call update_accum_rate
      call get_accum_rate(0, accum_rate)
      time_step = -log(ran_time)/accum_rate
      if ((loop_kmc_time + time_step > t) .and. (num_iter > 0)) then
        call random_seed(put=state)
        exit
      else
        call update_clocks(ran_time)
        call update_integ_rate
        call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
        call run_proc_nr(proc_nr, nr_site)
        loop_kmc_time = loop_kmc_time + time_step
        num_iter = num_iter + 1
      end if
    end do
end subroutine do_kmc_steps_time

subroutine do_kmc_step()

!****f* proclist/do_kmc_step
! FUNCTION
!    Performs exactly one kMC step.
!    *  first update clock
!    *  then configuration sampling step
!    *  last execute process
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_site, proc_nr, nr_site)
    call run_proc_nr(proc_nr, nr_site)
end subroutine do_kmc_step

subroutine get_next_kmc_step(proc_nr, nr_site)

!****f* proclist/get_kmc_step
! FUNCTION
!    Determines next step without executing it.
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint), intent(out) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call determine_procsite(ran_proc, ran_time, proc_nr, nr_site)

end subroutine get_next_kmc_step

subroutine get_occupation(occupation)

!****f* proclist/get_occupation
! FUNCTION
!    Evaluate current lattice configuration and returns
!    the normalized occupation as matrix. Different species
!    run along the first axis and different sites run
!    along the second.
!
! ARGUMENTS
!
!    ``none``
!******
    ! nr_of_species = 3, spuck = 2
    real(kind=rdouble), dimension(0:2, 1:2), intent(out) :: occupation

    integer(kind=iint) :: i, j, k, nr, species

    occupation = 0

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    ! shift position by 1, so it can be accessed
                    ! more straightforwardly from f2py interface
                    species = get_species((/i,j,k,nr/))
                    if(species.ne.null_species) then
                    occupation(species, nr) = &
                        occupation(species, nr) + 1
                    endif
                end do
            end do
        end do
    end do

    occupation = occupation/real(system_size(1)*system_size(2)*system_size(3))
end subroutine get_occupation

subroutine init(input_system_size, system_name, layer, seed_in, no_banner)

!****f* proclist/init
! FUNCTION
!     Allocates the system and initializes all sites in the given
!     layer.
!
! ARGUMENTS
!
!    * ``input_system_size`` number of unit cell per axis.
!    * ``system_name`` identifier for reload file.
!    * ``layer`` initial layer.
!    * ``no_banner`` [optional] if True no copyright is issued.
!******
    integer(kind=iint), intent(in) :: layer, seed_in
    integer(kind=iint), dimension(2), intent(in) :: input_system_size

    character(len=400), intent(in) :: system_name

    logical, optional, intent(in) :: no_banner

    if (.not. no_banner) then
        print *, "+------------------------------------------------------------+"
        print *, "|                                                            |"
        print *, "| This kMC Model 'MySecondTPR' was written by                |"
        print *, "|                                                            |"
        print *, "|           Max J. Hoffmann (mjhoffmann@gmail.com)           |"
        print *, "|                                                            |"
        print *, "| and implemented with the help of kmcos,                    |"
        print *, "| which is distributed under GNU/GPL Version 3               |"
        print *, "| (C) Max J. Hoffmann mjhoffmann@gmail.com                   |"
        print *, "|                                                            |"
        print *, "| kmcos is distributed in the hope that it will be useful    |"
        print *, "| but WITHOUT ANY WARRANTY; without even the implied         |"
        print *, "| warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR    |"
        print *, "| PURPOSE. See the GNU General Public License for more       |"
        print *, "| details.                                                   |"
        print *, "|                                                            |"
        print *, "| If using kmcos for a publication, attribution is           |"
        print *, "| greatly appreciated.                                       |"
        print *, "| Hoffmann, M. J., Matera, S., & Reuter, K. (2014).          |"
        print *, "| kmos: A lattice kinetic Monte Carlo framework.             |"
        print *, "| Computer Physics Communications, 185(7), 2138-2150.        |"
        print *, "|                                                            |"
        print *, "| Development https://github.com/kmcos/kmcos                 |"
        print *, "| Documentation https://kmcos.readthedocs.io                 |"
        print *, "| Reference https://dx.doi.org/10.1016/j.cpc.2014.04.003     |"
        print *, "|                                                            |"
        print *, "+------------------------------------------------------------+"
        print *, ""
        print *, ""
    endif
    call allocate_system(nr_of_proc, input_system_size, system_name)
    call initialize_state(layer, seed_in)
end subroutine init

function get_seed() result(state)
!****f* proclist/get_seed
! FUNCTION
!   Function to retrieve the state of the random number generator to
!    permit reproducible restart trajectories.
!
! ARGUMENTS
!
!    * None
!******
    integer :: state(33)
    call random_seed(get=state)
end function get_seed

subroutine put_seed(state)
!****f* proclist/put_seed
! FUNCTION
!    Subroutine to set the state of the random number generator to
!    permit reproducible restart trajectories.
!
! ARGUMENTS
!
!    * ``state`` an array of integers with the state of the random number
!    generator (input)
!******  
    integer, intent(in) :: state(33)
    call random_seed(put=state)
end subroutine put_seed 

function seed_gen(sd) result(sarr)
!****f* proclist/seed_gen
! FUNCTION
!    Function to transform a single number into a full set of integers
!    required for initializing the random number generator.
!
! ARGUMENTS
!
!    * ``sd`` an integer used to seed a simple random number generator
!    used to generate additional integers for seeding the production random
!    number generator (input)
!******


    integer, intent(in) :: sd
    integer(kind=ilong) :: s
    integer(kind=ilong) :: sarr(33)
    integer :: i

!Generate the state array with a simple linear congruential generator. The
!parameters for this generator are taken from the gfortran documentation on
!random_seed().

!Initialize the generator
    if (sd == 0) then
      s = 104729
    else
      s = mod(sd, 4294967296_ilong)
    end if

!Get values for the seed array
    do i =1, size(sarr)
      s = mod(s * 279470273_ilong, 4294967291_ilong)
      sarr(i) = int(mod(s, int(huge(0), ilong)), kind(0))
      s = mod(s, 4294967296_ilong)
    end do

end function seed_gen
subroutine initialize_state(layer, seed_in)

!****f* proclist/initialize_state
! FUNCTION
!    Initialize all sites and book-keeping array
!    for the given layer.
!
! ARGUMENTS
!
!    * ``layer`` integer representing layer
!******
    integer(kind=iint), intent(in) :: layer, seed_in

    integer(kind=iint) :: i, j, k, nr
    ! initialize random number generator
    allocate(seed_arr(seed_size))
    seed = seed_in
    seed_arr = seed_gen(seed)
    call random_seed(size=seed_size)
    call random_seed(put=seed_arr)
    deallocate(seed_arr)
    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    call reset_site((/i, j, k, nr/), null_species)
                end do
                select case(layer)
                case (ruo2)
                    call replace_species((/i, j, k, ruo2_bridge/), null_species, default_species)
                    call replace_species((/i, j, k, ruo2_cus/), null_species, default_species)
                end select
            end do
        end do
    end do

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                select case(layer)
                case(ruo2)
                    call touchup_ruo2_bridge((/i, j, k, ruo2_bridge/))
                    call touchup_ruo2_cus((/i, j, k, ruo2_cus/))
                end select
            end do
        end do
    end do


end subroutine initialize_state

subroutine run_proc_nr(proc, nr_site)

!****f* proclist/run_proc_nr
! FUNCTION
!    Runs process ``proc`` on site ``nr_site``.
!
! ARGUMENTS
!
!    * ``proc`` integer representing the process number
!    * ``nr_site``  integer representing the site
!******
    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), intent(in) :: nr_site

    integer(kind=iint), dimension(4) :: lsite

    call increment_procstat(proc)

    ! lsite = lattice_site, (vs. scalar site)
    lsite = nr2lattice(nr_site, :)

    select case(proc)
    case(CO_adsorption_bridge)
        call put_CO_ruo2_bridge(lsite)

    case(CO_adsorption_cus)
        call put_CO_ruo2_cus(lsite)

    case(CO_desorption_bridge)
        call take_CO_ruo2_bridge(lsite)

    case(CO_desorption_cus)
        call take_CO_ruo2_cus(lsite)

    case(COdiff_bridge_down)
        call take_CO_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call put_CO_ruo2_bridge(lsite)

    case(COdiff_bridge_left)
        call take_CO_ruo2_bridge(lsite)
        call put_CO_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(COdiff_bridge_right)
        call take_CO_ruo2_bridge(lsite)
        call put_CO_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(COdiff_bridge_up)
        call take_CO_ruo2_bridge(lsite)
        call put_CO_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(COdiff_cus_down)
        call take_CO_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call put_CO_ruo2_cus(lsite)

    case(COdiff_cus_left)
        call take_CO_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_CO_ruo2_bridge(lsite)

    case(COdiff_cus_right)
        call take_CO_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_CO_ruo2_bridge(lsite)

    case(COdiff_cus_up)
        call take_CO_ruo2_cus(lsite)
        call put_CO_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(O2_adsorption_bridge_right)
        call put_O_ruo2_bridge(lsite)
        call put_O_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(O2_adsorption_bridge_up)
        call put_O_ruo2_bridge(lsite)
        call put_O_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(O2_adsorption_cus_right)
        call put_O_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_O_ruo2_bridge(lsite)

    case(O2_adsorption_cus_up)
        call put_O_ruo2_cus(lsite)
        call put_O_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(O2_desorption_bridge_right)
        call take_O_ruo2_bridge(lsite)
        call take_O_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(O2_desorption_bridge_up)
        call take_O_ruo2_bridge(lsite)
        call take_O_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(O2_desorption_cus_right)
        call take_O_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call take_O_ruo2_bridge(lsite)

    case(O2_desorption_cus_up)
        call take_O_ruo2_cus(lsite)
        call take_O_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(Odiff_bridge_down)
        call take_O_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call put_O_ruo2_bridge(lsite)

    case(Odiff_bridge_left)
        call take_O_ruo2_bridge(lsite)
        call put_O_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(Odiff_bridge_right)
        call take_O_ruo2_bridge(lsite)
        call put_O_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(Odiff_bridge_up)
        call take_O_ruo2_bridge(lsite)
        call put_O_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(Odiff_cus_down)
        call take_O_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call put_O_ruo2_cus(lsite)

    case(Odiff_cus_left)
        call take_O_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_O_ruo2_bridge(lsite)

    case(Odiff_cus_right)
        call take_O_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_O_ruo2_bridge(lsite)

    case(Odiff_cus_up)
        call take_O_ruo2_cus(lsite)
        call put_O_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(React_bridge_down)
        call take_O_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call take_CO_ruo2_bridge(lsite)

    case(React_bridge_left)
        call take_O_ruo2_bridge(lsite)
        call take_CO_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(React_bridge_right)
        call take_O_ruo2_bridge(lsite)
        call take_CO_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(React_bridge_up)
        call take_O_ruo2_bridge(lsite)
        call take_CO_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(React_cus_down)
        call take_O_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call take_CO_ruo2_cus(lsite)

    case(React_cus_left)
        call take_O_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))
        call take_CO_ruo2_bridge(lsite)

    case(React_cus_right)
        call take_O_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call take_CO_ruo2_bridge(lsite)

    case(React_cus_up)
        call take_O_ruo2_cus(lsite)
        call take_CO_ruo2_cus(lsite + (/0, 1, 0, 0/))

    end select

end subroutine run_proc_nr

subroutine put_CO_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, CO)

    ! disable affected processes
    if(avail_sites(CO_adsorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_adsorption_bridge, site)
    endif

    if(avail_sites(COdiff_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_bridge_down, site)
    endif

    if(avail_sites(COdiff_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(COdiff_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_left, site)
    endif

    if(avail_sites(COdiff_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_right, site)
    endif

    if(avail_sites(O2_adsorption_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_right, site)
    endif

    if(avail_sites(O2_adsorption_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_up, site)
    endif

    if(avail_sites(O2_adsorption_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(O2_adsorption_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_right, site)
    endif

    if(avail_sites(Odiff_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_bridge_down, site)
    endif

    if(avail_sites(Odiff_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_left, site)
    endif

    if(avail_sites(Odiff_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_right, site)
    endif

    ! enable affected processes
    call add_proc(CO_desorption_bridge, site)
    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(COdiff_bridge_down, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(React_bridge_up, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(COdiff_bridge_left, site)
    case(O)
        call add_proc(React_cus_right, site)
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(COdiff_bridge_right, site)
    case(O)
        call add_proc(React_cus_left, site)
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(COdiff_bridge_up, site)
    case(O)
        call add_proc(React_bridge_down, site)
    end select


end subroutine put_CO_ruo2_bridge

subroutine take_CO_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, CO, empty)

    ! disable affected processes
    if(avail_sites(CO_desorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_desorption_bridge, site)
    endif

    if(avail_sites(COdiff_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(COdiff_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_bridge_left, site)
    endif

    if(avail_sites(COdiff_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_bridge_right, site)
    endif

    if(avail_sites(COdiff_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_bridge_up, site)
    endif

    if(avail_sites(React_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_bridge_down, site)
    endif

    if(avail_sites(React_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(React_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(React_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_cus_left, site)
    endif

    if(avail_sites(React_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_cus_right, site)
    endif

    ! enable affected processes
    call add_proc(CO_adsorption_bridge, site)
    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_up, site)
    case(O)
        call add_proc(Odiff_bridge_down, site)
    case(CO)
        call add_proc(COdiff_bridge_down, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_up, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(Odiff_bridge_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(COdiff_bridge_up, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_right, site)
    case(O)
        call add_proc(Odiff_cus_left, site)
    case(CO)
        call add_proc(COdiff_cus_left, site)
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(O2_adsorption_cus_right, site)
    case(O)
        call add_proc(Odiff_cus_right, site)
    case(CO)
        call add_proc(COdiff_cus_right, site)
    end select


end subroutine take_CO_ruo2_bridge

subroutine put_CO_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, CO)

    ! disable affected processes
    if(avail_sites(CO_adsorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_adsorption_cus, site)
    endif

    if(avail_sites(COdiff_bridge_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_down, site)
    endif

    if(avail_sites(COdiff_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(O2_adsorption_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_adsorption_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_adsorption_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_up, site)
    endif

    if(avail_sites(O2_adsorption_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_bridge_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_down, site)
    endif

    if(avail_sites(Odiff_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    call add_proc(CO_desorption_cus, site)
    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(COdiff_cus_down, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(React_cus_up, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(COdiff_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(React_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(COdiff_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(React_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(COdiff_cus_up, site)
    case(O)
        call add_proc(React_cus_down, site)
    end select


end subroutine put_CO_ruo2_cus

subroutine take_CO_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, CO, empty)

    ! disable affected processes
    if(avail_sites(CO_desorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_desorption_cus, site)
    endif

    if(avail_sites(COdiff_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(COdiff_cus_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_up, site)
    endif

    if(avail_sites(React_bridge_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(React_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(React_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(React_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(React_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_cus_down, site)
    endif

    if(avail_sites(React_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(React_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    call add_proc(CO_adsorption_cus, site)
    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(O2_adsorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(Odiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(COdiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(Odiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(COdiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_cus_up, site)
    case(O)
        call add_proc(Odiff_cus_down, site)
    case(CO)
        call add_proc(COdiff_cus_down, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_cus_up, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(Odiff_cus_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(COdiff_cus_up, site + (/0, -1, 0, 0/))
    end select


end subroutine take_CO_ruo2_cus

subroutine put_O_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, O)

    ! disable affected processes
    if(avail_sites(CO_adsorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_adsorption_bridge, site)
    endif

    if(avail_sites(COdiff_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_bridge_down, site)
    endif

    if(avail_sites(COdiff_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(COdiff_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_left, site)
    endif

    if(avail_sites(COdiff_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_right, site)
    endif

    if(avail_sites(O2_adsorption_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_right, site)
    endif

    if(avail_sites(O2_adsorption_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_up, site)
    endif

    if(avail_sites(O2_adsorption_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(O2_adsorption_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_right, site)
    endif

    if(avail_sites(Odiff_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_bridge_down, site)
    endif

    if(avail_sites(Odiff_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_left, site)
    endif

    if(avail_sites(Odiff_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_right, site)
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(Odiff_bridge_right, site)
    case(O)
        call add_proc(O2_desorption_bridge_right, site)
    case(CO)
        call add_proc(React_bridge_right, site)
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(Odiff_bridge_up, site)
    case(O)
        call add_proc(O2_desorption_bridge_up, site)
    case(CO)
        call add_proc(React_bridge_up, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(Odiff_bridge_down, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(O2_desorption_bridge_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(React_bridge_down, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(Odiff_bridge_left, site)
    case(O)
        call add_proc(O2_desorption_cus_right, site)
    case(CO)
        call add_proc(React_bridge_left, site)
    end select


end subroutine put_O_ruo2_bridge

subroutine take_O_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, O, empty)

    ! disable affected processes
    if(avail_sites(O2_desorption_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_desorption_bridge_right, site)
    endif

    if(avail_sites(O2_desorption_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_desorption_bridge_up, site)
    endif

    if(avail_sites(O2_desorption_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_desorption_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(O2_desorption_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_desorption_cus_right, site)
    endif

    if(avail_sites(Odiff_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_bridge_left, site)
    endif

    if(avail_sites(Odiff_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_bridge_right, site)
    endif

    if(avail_sites(Odiff_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_bridge_up, site)
    endif

    if(avail_sites(React_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(React_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(React_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_bridge_left, site)
    endif

    if(avail_sites(React_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_bridge_right, site)
    endif

    if(avail_sites(React_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_bridge_up, site)
    endif

    ! enable affected processes
    call add_proc(CO_adsorption_bridge, site)
    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_up, site)
    case(O)
        call add_proc(Odiff_bridge_down, site)
    case(CO)
        call add_proc(COdiff_bridge_down, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_up, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(Odiff_bridge_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(COdiff_bridge_up, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_right, site)
    case(O)
        call add_proc(Odiff_cus_left, site)
    case(CO)
        call add_proc(COdiff_cus_left, site)
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(empty)
        call add_proc(O2_adsorption_cus_right, site)
    case(O)
        call add_proc(Odiff_cus_right, site)
    case(CO)
        call add_proc(COdiff_cus_right, site)
    end select


end subroutine take_O_ruo2_bridge

subroutine put_O_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, O)

    ! disable affected processes
    if(avail_sites(CO_adsorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(CO_adsorption_cus, site)
    endif

    if(avail_sites(COdiff_bridge_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(COdiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(COdiff_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(COdiff_cus_down, site)
    endif

    if(avail_sites(COdiff_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(COdiff_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(O2_adsorption_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_adsorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_adsorption_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_adsorption_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_up, site)
    endif

    if(avail_sites(O2_adsorption_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_adsorption_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_bridge_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_down, site)
    endif

    if(avail_sites(Odiff_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(Odiff_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(O2_desorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(React_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(Odiff_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(O2_desorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(React_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(Odiff_cus_up, site)
    case(O)
        call add_proc(O2_desorption_cus_up, site)
    case(CO)
        call add_proc(React_cus_up, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(Odiff_cus_down, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(O2_desorption_cus_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(React_cus_down, site + (/0, -1, 0, 0/))
    end select


end subroutine put_O_ruo2_cus

subroutine take_O_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, O, empty)

    ! disable affected processes
    if(avail_sites(O2_desorption_bridge_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_desorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_desorption_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(O2_desorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(O2_desorption_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(O2_desorption_cus_up, site)
    endif

    if(avail_sites(O2_desorption_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(O2_desorption_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(Odiff_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(Odiff_cus_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(Odiff_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(Odiff_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(Odiff_cus_up, site)
    endif

    if(avail_sites(React_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(React_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(React_cus_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(React_cus_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(React_cus_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(React_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(React_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(React_cus_up, site)
    endif

    ! enable affected processes
    call add_proc(CO_adsorption_cus, site)
    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(O2_adsorption_cus_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(Odiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(COdiff_bridge_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(empty)
        call add_proc(O2_adsorption_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(O)
        call add_proc(Odiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(CO)
        call add_proc(COdiff_bridge_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_cus_up, site)
    case(O)
        call add_proc(Odiff_cus_down, site)
    case(CO)
        call add_proc(COdiff_cus_down, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(empty)
        call add_proc(O2_adsorption_cus_up, site + (/0, -1, 0, 0/))
    case(O)
        call add_proc(Odiff_cus_up, site + (/0, -1, 0, 0/))
    case(CO)
        call add_proc(COdiff_cus_up, site + (/0, -1, 0, 0/))
    end select


end subroutine take_O_ruo2_cus

subroutine touchup_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    if (can_do(CO_adsorption_bridge, site)) then
        call del_proc(CO_adsorption_bridge, site)
    endif
    if (can_do(CO_adsorption_cus, site)) then
        call del_proc(CO_adsorption_cus, site)
    endif
    if (can_do(CO_desorption_bridge, site)) then
        call del_proc(CO_desorption_bridge, site)
    endif
    if (can_do(CO_desorption_cus, site)) then
        call del_proc(CO_desorption_cus, site)
    endif
    if (can_do(COdiff_bridge_down, site)) then
        call del_proc(COdiff_bridge_down, site)
    endif
    if (can_do(COdiff_bridge_left, site)) then
        call del_proc(COdiff_bridge_left, site)
    endif
    if (can_do(COdiff_bridge_right, site)) then
        call del_proc(COdiff_bridge_right, site)
    endif
    if (can_do(COdiff_bridge_up, site)) then
        call del_proc(COdiff_bridge_up, site)
    endif
    if (can_do(COdiff_cus_down, site)) then
        call del_proc(COdiff_cus_down, site)
    endif
    if (can_do(COdiff_cus_left, site)) then
        call del_proc(COdiff_cus_left, site)
    endif
    if (can_do(COdiff_cus_right, site)) then
        call del_proc(COdiff_cus_right, site)
    endif
    if (can_do(COdiff_cus_up, site)) then
        call del_proc(COdiff_cus_up, site)
    endif
    if (can_do(O2_adsorption_bridge_right, site)) then
        call del_proc(O2_adsorption_bridge_right, site)
    endif
    if (can_do(O2_adsorption_bridge_up, site)) then
        call del_proc(O2_adsorption_bridge_up, site)
    endif
    if (can_do(O2_adsorption_cus_right, site)) then
        call del_proc(O2_adsorption_cus_right, site)
    endif
    if (can_do(O2_adsorption_cus_up, site)) then
        call del_proc(O2_adsorption_cus_up, site)
    endif
    if (can_do(O2_desorption_bridge_right, site)) then
        call del_proc(O2_desorption_bridge_right, site)
    endif
    if (can_do(O2_desorption_bridge_up, site)) then
        call del_proc(O2_desorption_bridge_up, site)
    endif
    if (can_do(O2_desorption_cus_right, site)) then
        call del_proc(O2_desorption_cus_right, site)
    endif
    if (can_do(O2_desorption_cus_up, site)) then
        call del_proc(O2_desorption_cus_up, site)
    endif
    if (can_do(Odiff_bridge_down, site)) then
        call del_proc(Odiff_bridge_down, site)
    endif
    if (can_do(Odiff_bridge_left, site)) then
        call del_proc(Odiff_bridge_left, site)
    endif
    if (can_do(Odiff_bridge_right, site)) then
        call del_proc(Odiff_bridge_right, site)
    endif
    if (can_do(Odiff_bridge_up, site)) then
        call del_proc(Odiff_bridge_up, site)
    endif
    if (can_do(Odiff_cus_down, site)) then
        call del_proc(Odiff_cus_down, site)
    endif
    if (can_do(Odiff_cus_left, site)) then
        call del_proc(Odiff_cus_left, site)
    endif
    if (can_do(Odiff_cus_right, site)) then
        call del_proc(Odiff_cus_right, site)
    endif
    if (can_do(Odiff_cus_up, site)) then
        call del_proc(Odiff_cus_up, site)
    endif
    if (can_do(React_bridge_down, site)) then
        call del_proc(React_bridge_down, site)
    endif
    if (can_do(React_bridge_left, site)) then
        call del_proc(React_bridge_left, site)
    endif
    if (can_do(React_bridge_right, site)) then
        call del_proc(React_bridge_right, site)
    endif
    if (can_do(React_bridge_up, site)) then
        call del_proc(React_bridge_up, site)
    endif
    if (can_do(React_cus_down, site)) then
        call del_proc(React_cus_down, site)
    endif
    if (can_do(React_cus_left, site)) then
        call del_proc(React_cus_left, site)
    endif
    if (can_do(React_cus_right, site)) then
        call del_proc(React_cus_right, site)
    endif
    if (can_do(React_cus_up, site)) then
        call del_proc(React_cus_up, site)
    endif
    select case(get_species(site))
    case(empty)
        call add_proc(CO_adsorption_bridge, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(O2_adsorption_bridge_up, site)
        case(O)
            call add_proc(Odiff_bridge_down, site)
        case(CO)
            call add_proc(COdiff_bridge_down, site)
        end select

        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(O2_adsorption_bridge_right, site)
        case(O)
            call add_proc(Odiff_cus_left, site)
        case(CO)
            call add_proc(COdiff_cus_left, site)
        end select

        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(O2_adsorption_cus_right, site)
        case(O)
            call add_proc(Odiff_cus_right, site)
        case(CO)
            call add_proc(COdiff_cus_right, site)
        end select

    case(O)
        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(Odiff_bridge_right, site)
        case(O)
            call add_proc(O2_desorption_bridge_right, site)
        case(CO)
            call add_proc(React_bridge_right, site)
        end select

        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(Odiff_bridge_up, site)
        case(O)
            call add_proc(O2_desorption_bridge_up, site)
        case(CO)
            call add_proc(React_bridge_up, site)
        end select

        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(Odiff_bridge_left, site)
        case(O)
            call add_proc(O2_desorption_cus_right, site)
        case(CO)
            call add_proc(React_bridge_left, site)
        end select

    case(CO)
        call add_proc(CO_desorption_bridge, site)
        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(COdiff_bridge_left, site)
        case(O)
            call add_proc(React_cus_right, site)
        end select

        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(empty)
            call add_proc(COdiff_bridge_right, site)
        case(O)
            call add_proc(React_cus_left, site)
        end select

        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(COdiff_bridge_up, site)
        case(O)
            call add_proc(React_bridge_down, site)
        end select

    end select

end subroutine touchup_ruo2_bridge

subroutine touchup_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    if (can_do(CO_adsorption_bridge, site)) then
        call del_proc(CO_adsorption_bridge, site)
    endif
    if (can_do(CO_adsorption_cus, site)) then
        call del_proc(CO_adsorption_cus, site)
    endif
    if (can_do(CO_desorption_bridge, site)) then
        call del_proc(CO_desorption_bridge, site)
    endif
    if (can_do(CO_desorption_cus, site)) then
        call del_proc(CO_desorption_cus, site)
    endif
    if (can_do(COdiff_bridge_down, site)) then
        call del_proc(COdiff_bridge_down, site)
    endif
    if (can_do(COdiff_bridge_left, site)) then
        call del_proc(COdiff_bridge_left, site)
    endif
    if (can_do(COdiff_bridge_right, site)) then
        call del_proc(COdiff_bridge_right, site)
    endif
    if (can_do(COdiff_bridge_up, site)) then
        call del_proc(COdiff_bridge_up, site)
    endif
    if (can_do(COdiff_cus_down, site)) then
        call del_proc(COdiff_cus_down, site)
    endif
    if (can_do(COdiff_cus_left, site)) then
        call del_proc(COdiff_cus_left, site)
    endif
    if (can_do(COdiff_cus_right, site)) then
        call del_proc(COdiff_cus_right, site)
    endif
    if (can_do(COdiff_cus_up, site)) then
        call del_proc(COdiff_cus_up, site)
    endif
    if (can_do(O2_adsorption_bridge_right, site)) then
        call del_proc(O2_adsorption_bridge_right, site)
    endif
    if (can_do(O2_adsorption_bridge_up, site)) then
        call del_proc(O2_adsorption_bridge_up, site)
    endif
    if (can_do(O2_adsorption_cus_right, site)) then
        call del_proc(O2_adsorption_cus_right, site)
    endif
    if (can_do(O2_adsorption_cus_up, site)) then
        call del_proc(O2_adsorption_cus_up, site)
    endif
    if (can_do(O2_desorption_bridge_right, site)) then
        call del_proc(O2_desorption_bridge_right, site)
    endif
    if (can_do(O2_desorption_bridge_up, site)) then
        call del_proc(O2_desorption_bridge_up, site)
    endif
    if (can_do(O2_desorption_cus_right, site)) then
        call del_proc(O2_desorption_cus_right, site)
    endif
    if (can_do(O2_desorption_cus_up, site)) then
        call del_proc(O2_desorption_cus_up, site)
    endif
    if (can_do(Odiff_bridge_down, site)) then
        call del_proc(Odiff_bridge_down, site)
    endif
    if (can_do(Odiff_bridge_left, site)) then
        call del_proc(Odiff_bridge_left, site)
    endif
    if (can_do(Odiff_bridge_right, site)) then
        call del_proc(Odiff_bridge_right, site)
    endif
    if (can_do(Odiff_bridge_up, site)) then
        call del_proc(Odiff_bridge_up, site)
    endif
    if (can_do(Odiff_cus_down, site)) then
        call del_proc(Odiff_cus_down, site)
    endif
    if (can_do(Odiff_cus_left, site)) then
        call del_proc(Odiff_cus_left, site)
    endif
    if (can_do(Odiff_cus_right, site)) then
        call del_proc(Odiff_cus_right, site)
    endif
    if (can_do(Odiff_cus_up, site)) then
        call del_proc(Odiff_cus_up, site)
    endif
    if (can_do(React_bridge_down, site)) then
        call del_proc(React_bridge_down, site)
    endif
    if (can_do(React_bridge_left, site)) then
        call del_proc(React_bridge_left, site)
    endif
    if (can_do(React_bridge_right, site)) then
        call del_proc(React_bridge_right, site)
    endif
    if (can_do(React_bridge_up, site)) then
        call del_proc(React_bridge_up, site)
    endif
    if (can_do(React_cus_down, site)) then
        call del_proc(React_cus_down, site)
    endif
    if (can_do(React_cus_left, site)) then
        call del_proc(React_cus_left, site)
    endif
    if (can_do(React_cus_right, site)) then
        call del_proc(React_cus_right, site)
    endif
    if (can_do(React_cus_up, site)) then
        call del_proc(React_cus_up, site)
    endif
    select case(get_species(site))
    case(empty)
        call add_proc(CO_adsorption_cus, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(O2_adsorption_cus_up, site)
        case(O)
            call add_proc(Odiff_cus_down, site)
        case(CO)
            call add_proc(COdiff_cus_down, site)
        end select

    case(O)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(Odiff_cus_up, site)
        case(O)
            call add_proc(O2_desorption_cus_up, site)
        case(CO)
            call add_proc(React_cus_up, site)
        end select

    case(CO)
        call add_proc(CO_desorption_cus, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(empty)
            call add_proc(COdiff_cus_up, site)
        case(O)
            call add_proc(React_cus_down, site)
        end select

    end select

end subroutine touchup_ruo2_cus

end module proclist
