!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Max J. Hoffmann.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
module proclist_pars
use kind_values
use base, only: &
    rates
use proclist_constants
use lattice, only: &
    default, &
    default_a, &
    get_species

implicit none

! User parameters
integer(kind=iint), public :: A = 1
integer(kind=iint), public :: E_bind_CO = 2
integer(kind=iint), public :: E_bind_O2 = 3
integer(kind=iint), public :: E_react = 4
integer(kind=iint), public :: T = 5
integer(kind=iint), public :: p_COgas = 6
integer(kind=iint), public :: p_O2gas = 7
real(kind=rdouble), public, dimension(7) :: userpar

! Constants
real(kind=rdouble), parameter :: bar = 1.0000000000e+05
real(kind=rdouble), parameter :: eV = 1.6021765650e-19
real(kind=rdouble), parameter :: h = 6.6260695700e-34
real(kind=rdouble), parameter :: kboltzmann = 1.3806488000e-23
real(kind=rdouble), parameter :: pi = 3.1415926536e+00
real(kind=rdouble), parameter :: umass = 1.6605389210e-27

! Species masses
real(kind=rdouble), parameter :: m_CO = 2.8010000000e+01
real(kind=rdouble), parameter :: m_O2 = 3.1998000000e+01
character(len=0), parameter, public :: byst_AB_react_down = ""
character(len=0), parameter, public :: byst_AB_react_left = ""
character(len=0), parameter, public :: byst_AB_react_right = ""
character(len=0), parameter, public :: byst_AB_react_up = ""
character(len=0), parameter, public :: byst_A_adsorption = ""
character(len=0), parameter, public :: byst_A_desorption = ""
character(len=0), parameter, public :: byst_B_adsorption = ""
character(len=0), parameter, public :: byst_B_desorption = ""

contains
subroutine update_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(in) :: val
    userpar(param) = val
end subroutine update_user_parameter

subroutine get_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(out) :: val
    val = userpar(param)
end subroutine get_user_parameter


function gr_AB_react_down(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_AB_react_down


    gr_AB_react_down = rate_AB_react_down()
    return

end function gr_AB_react_down

function rate_AB_react_down()


    real(kind=rdouble) :: rate_AB_react_down
    rate_AB_react_down = rates(AB_react_down)
    return

end function rate_AB_react_down


function gr_AB_react_left(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_AB_react_left


    gr_AB_react_left = rate_AB_react_left()
    return

end function gr_AB_react_left

function rate_AB_react_left()


    real(kind=rdouble) :: rate_AB_react_left
    rate_AB_react_left = rates(AB_react_left)
    return

end function rate_AB_react_left


function gr_AB_react_right(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_AB_react_right


    gr_AB_react_right = rate_AB_react_right()
    return

end function gr_AB_react_right

function rate_AB_react_right()


    real(kind=rdouble) :: rate_AB_react_right
    rate_AB_react_right = rates(AB_react_right)
    return

end function rate_AB_react_right


function gr_AB_react_up(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_AB_react_up


    gr_AB_react_up = rate_AB_react_up()
    return

end function gr_AB_react_up

function rate_AB_react_up()


    real(kind=rdouble) :: rate_AB_react_up
    rate_AB_react_up = rates(AB_react_up)
    return

end function rate_AB_react_up


function gr_A_adsorption(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_A_adsorption


    gr_A_adsorption = rate_A_adsorption()
    return

end function gr_A_adsorption

function rate_A_adsorption()


    real(kind=rdouble) :: rate_A_adsorption
    rate_A_adsorption = rates(A_adsorption)
    return

end function rate_A_adsorption


function gr_A_desorption(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_A_desorption


    gr_A_desorption = rate_A_desorption()
    return

end function gr_A_desorption

function rate_A_desorption()


    real(kind=rdouble) :: rate_A_desorption
    rate_A_desorption = rates(A_desorption)
    return

end function rate_A_desorption


function gr_B_adsorption(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_B_adsorption


    gr_B_adsorption = rate_B_adsorption()
    return

end function gr_B_adsorption

function rate_B_adsorption()


    real(kind=rdouble) :: rate_B_adsorption
    rate_B_adsorption = rates(B_adsorption)
    return

end function rate_B_adsorption


function gr_B_desorption(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_B_desorption


    gr_B_desorption = rate_B_desorption()
    return

end function gr_B_desorption

function rate_B_desorption()


    real(kind=rdouble) :: rate_B_desorption
    rate_B_desorption = rates(B_desorption)
    return

end function rate_B_desorption


end module proclist_pars
