!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Andreas Garhammer.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
module proclist_pars
use kind_values
use base, only: &
    rates
use proclist_constants
use lattice, only: &
    default, &
    default_a_1, &
    default_a_2, &
    default_b_1, &
    default_b_2, &
    get_species

implicit none

! User parameters
integer(kind=iint), public :: k = 1
real(kind=rdouble), public, dimension(1) :: userpar

! Constants

! Species masses
character(len=1), parameter, public :: byst_a_1_a_2 = ""
character(len=1), parameter, public :: byst_a_1_b_1 = ""
character(len=1), parameter, public :: byst_a_1_b_2 = ""
character(len=1), parameter, public :: byst_a_2_a_1 = ""
character(len=1), parameter, public :: byst_a_2_b_1 = ""
character(len=1), parameter, public :: byst_a_2_b_2 = ""
character(len=1), parameter, public :: byst_b_1_a_1 = ""
character(len=1), parameter, public :: byst_b_1_a_2 = ""
character(len=1), parameter, public :: byst_b_1_b_2 = ""
character(len=1), parameter, public :: byst_b_2_a_1 = ""
character(len=1), parameter, public :: byst_b_2_a_2 = ""
character(len=1), parameter, public :: byst_b_2_b_1 = ""

contains
subroutine update_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(in) :: val
    userpar(param) = val
end subroutine update_user_parameter

subroutine get_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(out) :: val
    val = userpar(param)
end subroutine get_user_parameter


function gr_a_1_a_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_1_a_2


    gr_a_1_a_2 = rate_a_1_a_2()
    return

end function gr_a_1_a_2

function rate_a_1_a_2()


    real(kind=rdouble) :: rate_a_1_a_2
    rate_a_1_a_2 = rates(a_1_a_2)
    return

end function rate_a_1_a_2


function gr_a_1_b_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_1_b_1


    gr_a_1_b_1 = rate_a_1_b_1()
    return

end function gr_a_1_b_1

function rate_a_1_b_1()


    real(kind=rdouble) :: rate_a_1_b_1
    rate_a_1_b_1 = rates(a_1_b_1)
    return

end function rate_a_1_b_1


function gr_a_1_b_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_1_b_2


    gr_a_1_b_2 = rate_a_1_b_2()
    return

end function gr_a_1_b_2

function rate_a_1_b_2()


    real(kind=rdouble) :: rate_a_1_b_2
    rate_a_1_b_2 = rates(a_1_b_2)
    return

end function rate_a_1_b_2


function gr_a_2_a_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_2_a_1


    gr_a_2_a_1 = rate_a_2_a_1()
    return

end function gr_a_2_a_1

function rate_a_2_a_1()


    real(kind=rdouble) :: rate_a_2_a_1
    rate_a_2_a_1 = rates(a_2_a_1)
    return

end function rate_a_2_a_1


function gr_a_2_b_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_2_b_1


    gr_a_2_b_1 = rate_a_2_b_1()
    return

end function gr_a_2_b_1

function rate_a_2_b_1()


    real(kind=rdouble) :: rate_a_2_b_1
    rate_a_2_b_1 = rates(a_2_b_1)
    return

end function rate_a_2_b_1


function gr_a_2_b_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_a_2_b_2


    gr_a_2_b_2 = rate_a_2_b_2()
    return

end function gr_a_2_b_2

function rate_a_2_b_2()


    real(kind=rdouble) :: rate_a_2_b_2
    rate_a_2_b_2 = rates(a_2_b_2)
    return

end function rate_a_2_b_2


function gr_b_1_a_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_1_a_1


    gr_b_1_a_1 = rate_b_1_a_1()
    return

end function gr_b_1_a_1

function rate_b_1_a_1()


    real(kind=rdouble) :: rate_b_1_a_1
    rate_b_1_a_1 = rates(b_1_a_1)
    return

end function rate_b_1_a_1


function gr_b_1_a_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_1_a_2


    gr_b_1_a_2 = rate_b_1_a_2()
    return

end function gr_b_1_a_2

function rate_b_1_a_2()


    real(kind=rdouble) :: rate_b_1_a_2
    rate_b_1_a_2 = rates(b_1_a_2)
    return

end function rate_b_1_a_2


function gr_b_1_b_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_1_b_2


    gr_b_1_b_2 = rate_b_1_b_2()
    return

end function gr_b_1_b_2

function rate_b_1_b_2()


    real(kind=rdouble) :: rate_b_1_b_2
    rate_b_1_b_2 = rates(b_1_b_2)
    return

end function rate_b_1_b_2


function gr_b_2_a_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_2_a_1


    gr_b_2_a_1 = rate_b_2_a_1()
    return

end function gr_b_2_a_1

function rate_b_2_a_1()


    real(kind=rdouble) :: rate_b_2_a_1
    rate_b_2_a_1 = rates(b_2_a_1)
    return

end function rate_b_2_a_1


function gr_b_2_a_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_2_a_2


    gr_b_2_a_2 = rate_b_2_a_2()
    return

end function gr_b_2_a_2

function rate_b_2_a_2()


    real(kind=rdouble) :: rate_b_2_a_2
    rate_b_2_a_2 = rates(b_2_a_2)
    return

end function rate_b_2_a_2


function gr_b_2_b_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_b_2_b_1


    gr_b_2_b_1 = rate_b_2_b_1()
    return

end function gr_b_2_b_1

function rate_b_2_b_1()


    real(kind=rdouble) :: rate_b_2_b_1
    rate_b_2_b_1 = rates(b_2_b_1)
    return

end function rate_b_2_b_1


end module proclist_pars
