!  This file was generated by kmcos (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Andreas Garhammer.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmcos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist_constants
use kind_values
use lattice, only: &
    default, &
    default_a_1, &
    default_a_2, &
    default_b_1, &
    default_b_2, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 2
integer(kind=iint), parameter, public :: empty = 0
integer(kind=iint), parameter, public :: ion = 1
integer(kind=iint), public :: default_species = empty

! Process constants

integer(kind=iint), parameter, public :: a_1_a_2 = 1
integer(kind=iint), parameter, public :: a_1_b_1 = 2
integer(kind=iint), parameter, public :: a_1_b_2 = 3
integer(kind=iint), parameter, public :: a_2_a_1 = 4
integer(kind=iint), parameter, public :: a_2_b_1 = 5
integer(kind=iint), parameter, public :: a_2_b_2 = 6
integer(kind=iint), parameter, public :: b_1_a_1 = 7
integer(kind=iint), parameter, public :: b_1_a_2 = 8
integer(kind=iint), parameter, public :: b_1_b_2 = 9
integer(kind=iint), parameter, public :: b_2_a_1 = 10
integer(kind=iint), parameter, public :: b_2_a_2 = 11
integer(kind=iint), parameter, public :: b_2_b_1 = 12

end module proclist_constants
