#!/bin/bash -eu


# These have been removed from the below list.       python-dev \     python-glade2 \ gazpacho \    python-kiwi \                       python-pygoocanvas \                      python-lxml \                     python-matplotlib \                      python-lxml \               python-matplotlib \


# sudo add-apt-repository ppa:campos-dev/campos

print "Simple wrapping script that resolves"
print "dependency within the APT system"


sudo apt-get update
sudo apt-get install\
                     gfortran \
                     python-ase \
                     python3-gi \

pip install ase --user